[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--verbose",
    "--capture=no",
    "--strict-markers",
    "--tb=short"
]
markers = [
    "asyncio: mark test as async/await test",
    "slow: mark test as slow running",
    "integration: mark as integration test"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
]